### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by borkdude** [rorokimdim/stash#1]
If stash could provide a Windows binary then it would work in babashka on Windows too:

https://github.com/babashka/pod-registry/blob/master/manifests/rorokimdim/stash/0.2.0/manifest.edn

/cc @littleli

**Comment by borkdude** [comment]
Btw, Windows binaries can be built via Github Actions possibly.

**Comment by rorokimdim** [comment]
Thanks @borkdude I will see if i can figure it out 👍

**Comment by borkdude** [comment]
Side note: your pod is featured in this awesome youtube video:

https://www.youtube.com/watch?v=jm0RXmyjRJ8&ab_channel=onthecodeagain

**Comment by rorokimdim** [comment]
That's huge 🎉  thanks for sharing @borkdude

**Comment by rorokimdim** [comment]
I could not make the build work for windows, unfortunately.

One major blocker is the brick library which is used for the user-interface.  It has some dependencies that do not seem to work on windows.

It should be possible to pull out the user-interface code (which is only in app/Main.hs) but that will take some work.

Github Actions build error: https://github.com/rorokimdim/stash/runs/5613345800?check_suite_focus=true#step:5:907

Something that showed up when i googled: https://www.reddit.com/r/haskell/comments/7tutxa/vty_needs_your_help_supporting_windows/

**Comment by borkdude** [comment]
No problem, thanks for looking into it!

**Comment by rorokimdim** [comment]
I refactored the code slightly so we can build a minimal command for windows. 

Here is the binary but I have no idea how to test it at the moment since I don't have a windows machine.

https://github.com/rorokimdim/stash/releases/tag/v0.3.1

**Comment by borkdude** [comment]
Maybe @littleli?

**Comment by borkdude** [comment]
I can test later today on a Windows machine.

**Comment by borkdude** [comment]
@rorokimdim I tested it on a Windows machine and it seems to work fine!

``` clojure
C:\Temp> type stash.clj
(require '[babashka.pods :as pods])
(pods/load-pod "./stash-0.3.1-Windows-ghc-8.8.4.exe")
(require '[pod.rorokimdim.stash :as stash])

(ns-publics 'pod.rorokimdim.stash)

(stash/init {"encryption-key" "foo"
             "stash-path" "foo.stash"
             "create-stash-if-missing" true})

(prn (stash/version))

(stash/set :foo :bar "baz")

(prn (stash/get :foo :bar))
C:\Temp> bb .\stash.clj
"0.3.1"
"baz"
```

I do recommend using .zip files for releases like you did in 0.2.0. The pod registry expects this:

https://github.com/babashka/pod-registry/blob/master/manifests/rorokimdim/stash/0.2.0/manifest.edn

For macOS and linux .tar.gz is also fine.

**Comment by rorokimdim** [comment]
That is awesome. Thanks a lot @borkdude !

I will put it together.

**Comment by rorokimdim** [comment]
I hope I did this right https://github.com/babashka/pod-registry/pull/26

**Comment by borkdude** [comment]
Works great:

``` clojure
(require '[babashka.pods :as pods])

(pods/load-pod 'rorokimdim/stash "0.3.1")

(require '[pod.rorokimdim.stash :as stash])

(ns-publics 'pod.rorokimdim.stash)

(stash/init {"encryption-key" "foo"
             "stash-path" "foo.stash"
             "create-stash-if-missing" true})

(prn (stash/version))

(stash/set :foo :bar "baz")

(prn (stash/get :foo :bar))
```

**Comment by borkdude** [comment]
Also added an example: https://github.com/babashka/pod-registry/blob/master/examples/stash.clj

**Comment by rorokimdim** [comment]
> Also added an example: https://github.com/babashka/pod-registry/blob/master/examples/stash.clj

Perfect. Thank you!
