### ISSUE TITLE
How does the Cryptographic scheme of Stash work

### ISSUE THREAD

**Issue by judepayne** [rorokimdim/stash#3]
Hi,

wanted to understand how it all works!

- What hash algorithm is used to create the hash of the master password?

- Is that same (stored in the db) hash used to encrypt & decrypt data on nodes stored in the database? Of if something else, how is it generated? (and the salt)

I've tried tracing through the Haskell, but am not an expert and couldn't quite get there :) thanks!

**Comment by rorokimdim** [comment]
It uses sha512 with a random salt https://github.com/rorokimdim/stash/blob/master/src/Cipher.hs#L52-L65.

the hash salt is indeed stored in the sqlite db -- under `config` table:

```
sqlite3 [your-stash-file-path]

select * from config;
```

the hash-salt is only used when creating hashes of keys/values. 

The encryption scheme does not use the hashed values. all data is encrypted using AES256.

https://github.com/rorokimdim/stash/blob/master/src/Cipher.hs#L29-L50

(Having said that, I'm working on a similar project that is based on libsodium https://doc.libsodium.org/. But it's not ready to be open-sourced yet.)

**Comment by judepayne** [comment]
Thank you... but what is the key (padded or not) used for the AES encryption/ decryption (and where does it come from)? That's the part I was trying to trace through but didn't manage.

libsodium looks very interesting! a cross platform standard for securing data.

BTW, would it be possible to add a license for stash?

**Comment by rorokimdim** [comment]
Ah the AES encryption/decryption key is the passphrase of the stash file. It is read in either from console prompt or from `STASH_ENCRYPTION_KEY` env variable if it is set -- for babashka pod script you pass it in during stash/init call https://github.com/rorokimdim/stash/blob/master/scripting-examples/babashka/stash.clj#L25-L27

(On hindsight, i should have used the passphrase to encrypt a random encryption key and used the random encryption key for the data. the libsodium version will do that)

stash is made available under bsd-3 license https://github.com/rorokimdim/stash/blob/master/LICENSE

**Comment by judepayne** [comment]
Got it. Thanks very much!

**Comment by judepayne** [comment]
Actually @rorokimdim  last question about encryption! Would it not be better to use a stronger password hashing algorithm than sha512 for hashing the master password? e.g. something like bcrypt or scrypt.

**Comment by rorokimdim** [comment]
i picked sha512 + good random salt as it seemed good enough to me.

i could have avoided hashing or storing hashes altogether if i had designed the program differently. I am indeed working on a version that does that -- along with switching to using libsodium and lot of other things including a mobile app and a way to safely share data.

However, if you are are concerned about using sha512, it's not difficult to switch to anything you want (just these lines mostly https://github.com/rorokimdim/stash/blob/1b3fefab402c580a8e743119e69d71b3a25f42a4/src/Cipher.hs#L52-L65)

**Comment by judepayne** [comment]
Thanks @rorokimdim. Look forward to the next version (of this super useful utility). I hope it will come as a babashka pod at some point!

**Comment by rorokimdim** [comment]
@judepayne wondering if you'd be interested in trying out something I've been working on https://textlambda.com/. If you have suggestions or comments for me you can email me at amit@textlambda.com. 

While I see myself using it I'm not sure if it will appeal to anyone else.

Many thanks!

**Comment by judepayne** [comment]
@rorokimdim thanks for asking. Quite busy at the moment, but will try to get to it in the next ten days or so

**Comment by rorokimdim** [comment]
@judepayne of course! thank you very much
